"""Task 2-D — AI Lean proof generation with a mocked LLM and mocked Lake."""
from __future__ import annotations

import json
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from agent import lean_ai_proof, lean_bridge
from agent.config import AgentConfig
from agent.lean_ai_proof import (
    AI_PROOF_STRATEGY,
    assemble_ai_module,
    extract_lean_source,
    extract_tactic_script,
    find_trusted_statement,
    reject_unsound_lean_source,
    run_ai_proof_repair,
)


class ScriptedGenerator:
    """Deterministic ``AiProofGenerator``: returns canned Lean per call."""

    def __init__(self, replies: list[str]) -> None:
        self.replies = list(replies)
        self.requests: list[dict] = []

    def generate_lean_proof(self, request: dict) -> str:
        self.requests.append(request)
        if not self.replies:
            raise RuntimeError("no scripted reply left")
        return self.replies.pop(0)


def _good_module(theorem: str = "square_nonneg_correct") -> str:
    """An LLM reply echoing the (fixed) statement plus a tactic script."""
    return (
        "```lean\n"
        f"theorem {theorem} (x : Int) (result : Int) (h_body : result = squareNonnegResult x) :\n"
        "    (True) → (result ≥ 0) := by\n"
        "  intro _\n  rw [h_body]\n  exact mul_self_nonneg x\n```"
    )


BRIDGE_MODULE = """import MumeiLean

/-!
# Generated.Ai_e2e

Auto-generated by `scripts/ingest_cert.py` for mumei module `ai_e2e`.
-/

namespace Generated.Ai_e2e

open MumeiLean

def squareNonnegResult (x : Int) : Int :=
  x * x

-- mumei_escalation_reason: z3_unknown_complex_fragment
/-- Auto-generated from mumei atom `square_nonneg`. -/
theorem square_nonneg_correct (x : Int) (result : Int) (h_body : result = squareNonnegResult x) :
    (True) → (result ≥ 0) := by
  rw [h_body]
  unfold squareNonnegResult
  mumei_arith_deep

theorem other_correct : True := by
  sorry

end Generated.Ai_e2e
"""


def _fake_repo(tmp_path: Path, *, with_statement: bool = True) -> Path:
    repo = tmp_path / "mumei-lean"
    (repo / "scripts").mkdir(parents=True)
    (repo / "scripts" / "bridge.py").write_text("# stub\n")
    (repo / "scripts" / "export_cert.py").write_text(
        'TRANSLATOR_VERSION = "mumei-lean-translator-ir-v1"\n'
        'BRIDGE_LEMMA_HASH = "hash-for-test"\n',
        encoding="utf-8",
    )
    (repo / "lakefile.lean").write_text("-- stub\n")
    if with_statement:
        generated = repo / "generated" / "Generated"
        generated.mkdir(parents=True)
        (generated / "Ai_e2e.lean").write_text(BRIDGE_MODULE, encoding="utf-8")
    return repo


def _cert() -> dict:
    return {
        "all_verified": False,
        "atoms": [
            {"name": "ok", "z3_check_result": "unsat"},
            {
                "name": "square_nonneg",
                "z3_check_result": "unknown",
                "z3_result_class": "unknown",
                "escalation_reason": "z3_unknown_complex_fragment",
                "requires": "true",
                "ensures": "result >= 0",
                "body_expr": "x * x",
            },
        ],
    }


def _lake_ok() -> tuple[int, str]:
    return 0, (
        "info: 'Generated.AiProof.Square_nonneg.square_nonneg_correct' depends on "
        "axioms: [propext, Classical.choice, Quot.sound]\n"
        "Build completed successfully.\n"
    )


def _lake_unsolved() -> tuple[int, str]:
    return 1, "\nerror: unsolved goals\nx : Int\n⊢ 0 ≤ x * x"


def _patch_lake(**kwargs):
    """Patch the AI stage's Lake runner (``(returncode, log)``)."""
    return patch("agent.lean_ai_proof._lake_build_module", **kwargs)


@pytest.fixture(autouse=True)
def _lake_on_path() -> None:
    # ``shutil`` is one shared module object for lean_bridge / lean_ai_proof.
    with patch("agent.lean_ai_proof.shutil.which", return_value="/usr/bin/lake"):
        yield


# ---------------------------------------------------------------------------
# source hygiene
# ---------------------------------------------------------------------------


def test_extract_lean_source_strips_fences() -> None:
    assert extract_lean_source("```lean\ntheorem t : True := trivial\n```") == (
        "theorem t : True := trivial"
    )
    assert extract_lean_source("theorem t : True := trivial") == (
        "theorem t : True := trivial"
    )


@pytest.mark.parametrize(
    "source, expected",
    [
        ("sorry", "forbidden_token:sorry"),
        ("admit", "forbidden_token:admit"),
        ("exact bad\naxiom bad : False", "forbidden_token:axiom"),
        ("native_decide", "forbidden_token:native_decide"),
        ("run_tac do pure ()", "forbidden_token:run_tac"),
        ("set_option maxHeartbeats 0 in\n  simp", "forbidden_token:set_option"),
        ("trivial\ntheorem other : True := trivial", "forbidden_token:declaration"),
        ("", "empty_source"),
        ("intro _\nexact mul_self_nonneg x", None),
    ],
)
def test_reject_unsound_lean_source(source: str, expected: str | None) -> None:
    assert reject_unsound_lean_source(source, "t_correct") == expected


def test_extract_tactic_script_accepts_full_theorem_or_bare_tactics() -> None:
    assert extract_tactic_script(_good_module(), "square_nonneg_correct") == (
        "intro _\nrw [h_body]\nexact mul_self_nonneg x"
    )
    assert extract_tactic_script("```lean\n  simp\n  ring\n```", "t") == "simp\nring"
    assert extract_tactic_script("by\n  omega", "t") == "omega"
    # a *different* statement for the expected name is discarded: only the
    # tactic text survives, and it is spliced under the trusted header.
    assert extract_tactic_script(
        "theorem t_correct : True := by\n  trivial", "t_correct"
    ) == "trivial"


def test_trusted_statement_is_lifted_from_bridge_module(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path)
    stmt = find_trusted_statement(repo, "square_nonneg", theorem_name="square_nonneg_correct")
    assert stmt is not None
    assert stmt.namespace == "Generated.Ai_e2e"
    assert stmt.header.startswith("theorem square_nonneg_correct (x : Int) (result : Int)")
    assert stmt.header.endswith("(True) → (result ≥ 0)")
    assert "def squareNonnegResult" in stmt.preamble
    assert "other_correct" not in stmt.preamble
    assert "mumei_arith_deep" not in stmt.preamble
    module = assemble_ai_module(
        stmt, module="Generated.AiProof.Square_nonneg", tactics="trivial", nonce="n"
    )
    assert "namespace Generated.AiProof.Square_nonneg" in module
    assert module.rstrip().endswith("end Generated.AiProof.Square_nonneg")
    assert f"{stmt.header} := by\n  trivial" in module
    assert "#print axioms square_nonneg_correct" in module
    assert "sorry" not in module
    assert find_trusted_statement(repo, "nope", theorem_name="nope_correct") is None


def test_ai_proof_skips_atoms_without_trusted_statement(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path, with_statement=False)
    gen = ScriptedGenerator([_good_module()])
    with _patch_lake(return_value=_lake_ok()) as lake:
        result = run_ai_proof_repair(cert=_cert(), mumei_lean_repo=repo, generator=gen)
    assert result is not None
    assert gen.requests == []
    lake.assert_not_called()
    assert result["success"] is False
    assert result["error_code"] == "no_trusted_statement"
    assert result["ai_proof_residual"] == ["square_nonneg"]


def test_ai_proof_wrong_statement_cannot_certify_contract(tmp_path: Path) -> None:
    """`theorem square_nonneg_correct : True := by trivial` must not promote."""
    repo = _fake_repo(tmp_path)
    gen = ScriptedGenerator(["theorem square_nonneg_correct : True := by\n  trivial"])
    seen: list[str] = []

    def fake_lake(repo_path, module, *, timeout):
        src = (repo_path / "generated" / "Generated" / "AiProof" / "Square_nonneg.lean").read_text()
        seen.append(src)
        return 1, "error: unsolved goals\n⊢ result ≥ 0"

    with _patch_lake(side_effect=fake_lake):
        result = run_ai_proof_repair(
            cert=_cert(), mumei_lean_repo=repo, generator=gen, max_attempts=1
        )
    assert result is not None and result["success"] is False
    assert len(seen) == 1
    # the compiled statement is the translator's, not the model's
    assert ": True := by" not in seen[0]
    assert "(h_body : result = squareNonnegResult x)" in seen[0]
    assert "  trivial" in seen[0]


@pytest.mark.parametrize(
    "log, expected",
    [
        ("'X.t_correct' depends on axioms: [propext, sorryAx]", "unsound_axioms"),
        ("'X.t_correct' depends on axioms: [myAxiom]", "unsound_axioms"),
        ("'X.t_correct' depends on axioms: [propext, Classical.choice, Quot.sound]", None),
        ("'X.t_correct' does not depend on any axioms", None),
        ("Build completed successfully.", "axiom_audit_missing"),
    ],
)
def test_build_log_axiom_audit(log: str, expected: str | None) -> None:
    accepted, code = lean_ai_proof._build_log_accepts(0, log, theorem_name="t_correct")
    assert accepted is (expected is None)
    assert code == expected


def test_build_log_timeout_is_classified() -> None:
    accepted, code = lean_ai_proof._build_log_accepts(
        -1, "error: lake build timed out after 5 seconds"
    )
    assert accepted is False and code == "timeout"


def test_ai_proof_evidence_is_not_overwritten_across_runs(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path)
    evidence = tmp_path / "evidence"
    paths = []
    for reply in (_good_module(), "```lean\n  intro _\n  omega\n```"):
        with _patch_lake(return_value=_lake_ok()):
            result = run_ai_proof_repair(
                cert=_cert(),
                mumei_lean_repo=repo,
                generator=ScriptedGenerator([reply]),
                evidence_dir=evidence,
            )
        assert result is not None
        atom = next(a for a in result["lean_cert"]["atoms"] if a["name"] == "square_nonneg")
        paths.append(Path(atom["lean_metadata"]["proof_path"]))
    assert paths[0] != paths[1]
    assert "mul_self_nonneg" in paths[0].read_text()
    assert "omega" in paths[1].read_text()


# ---------------------------------------------------------------------------
# run_ai_proof_repair
# ---------------------------------------------------------------------------


def test_ai_proof_promotes_only_after_lake_success(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path)
    gen = ScriptedGenerator([_good_module()])
    evidence = tmp_path / "evidence"

    with _patch_lake(return_value=_lake_ok()) as run:
        result = run_ai_proof_repair(
            cert=_cert(),
            mumei_lean_repo=repo,
            generator=gen,
            evidence_dir=evidence,
        )

    assert result is not None
    assert result["success"] is True
    assert result["ai_proof_used"] is True
    assert result["ai_proof_proved"] == 1
    assert result["fallback_strategy"] == AI_PROOF_STRATEGY
    assert run.call_args.args[:2] == (repo, "Generated.AiProof.Square_nonneg")

    atom = next(a for a in result["lean_cert"]["atoms"] if a["name"] == "square_nonneg")
    assert atom["z3_check_result"] == "lean_verified"
    assert atom["lean_fallback_strategy"] == AI_PROOF_STRATEGY
    meta = atom["lean_metadata"]
    assert meta["ai_proof_used"] is True
    assert meta["known_witness_used"] is False
    assert meta["ai_proof_attempts"] == 1
    assert meta["lean_module"] == "Generated.AiProof.Square_nonneg"
    assert meta["theorem_name"] == "square_nonneg_correct"
    assert atom["translator_version"] == "mumei-lean-translator-ir-v1"
    assert atom["bridge_lemma_hash"] == "hash-for-test"
    assert atom["lean_result_metadata"]["ai_proof_used"] is True
    # evidence: source and build log persisted, module removed from checkout
    assert Path(meta["proof_path"]).read_text(encoding="utf-8").startswith("import MumeiLean")
    assert "Build completed" in Path(meta["build_log_path"]).read_text(encoding="utf-8")
    assert not (repo / "generated" / "Generated" / "AiProof" / "Square_nonneg.lean").exists()
    # unaffected atoms untouched
    assert next(a for a in result["lean_cert"]["atoms"] if a["name"] == "ok") == {
        "name": "ok",
        "z3_check_result": "unsat",
    }


def test_ai_proof_repairs_with_lean_feedback(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path)
    gen = ScriptedGenerator([_good_module(), _good_module()])

    with _patch_lake(
        side_effect=[_lake_unsolved(), _lake_ok()],
    ):
        result = run_ai_proof_repair(
            cert=_cert(),
            mumei_lean_repo=repo,
            generator=gen,
            max_attempts=3,
            evidence_dir=tmp_path / "evidence",
        )

    assert result is not None and result["success"] is True
    assert len(gen.requests) == 2
    assert gen.requests[0]["feedback"] == []
    feedback = gen.requests[1]["feedback"]
    assert feedback[0]["error_code"] == "tactic_failed"
    assert "unsolved goals" in feedback[0]["log_tail"]
    outcome = result["ai_proof_outcomes"][0]
    assert outcome["attempts"] == 2
    assert [a["accepted"] for a in outcome["attempt_log"]] == [False, True]
    atom = result["lean_cert"]["atoms"][1]
    assert atom["lean_metadata"]["ai_proof_attempts"] == 2


def test_ai_proof_keeps_unknown_when_all_attempts_fail(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path)
    gen = ScriptedGenerator([_good_module()] * 2)

    with _patch_lake(return_value=_lake_unsolved()):
        result = run_ai_proof_repair(
            cert=_cert(),
            mumei_lean_repo=repo,
            generator=gen,
            max_attempts=2,
            evidence_dir=tmp_path / "evidence",
        )

    assert result is not None
    assert result["success"] is False
    assert result["ai_proof_used"] is False
    assert result["error_code"] == "tactic_failed"
    assert result["ai_proof_residual"] == ["square_nonneg"]
    assert result["lean_cert"]["atoms"][1]["z3_check_result"] == "unknown"
    assert "lean_metadata" not in result["lean_cert"]["atoms"][1]
    assert len(gen.requests) == 2


def test_ai_proof_rejects_sorry_before_lake(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path)
    gen = ScriptedGenerator(
        ["theorem square_nonneg_correct : True := by sorry", _good_module()]
    )

    with _patch_lake(return_value=_lake_ok()) as run:
        result = run_ai_proof_repair(
            cert=_cert(),
            mumei_lean_repo=repo,
            generator=gen,
            evidence_dir=tmp_path / "evidence",
        )

    assert result is not None and result["success"] is True
    assert run.call_count == 1  # the sorry attempt never reached lake
    assert gen.requests[1]["feedback"][0]["rejection_reason"] == "forbidden_token:sorry"
    log = result["ai_proof_outcomes"][0]["attempt_log"]
    assert log[0]["error_code"] == "unsound_source"


def test_ai_proof_does_not_trust_exit_zero_with_sorry_warning(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path)
    gen = ScriptedGenerator([_good_module()])
    lake = (0, "warning: declaration uses 'sorry'\n")
    with _patch_lake(return_value=lake):
        result = run_ai_proof_repair(
            cert=_cert(),
            mumei_lean_repo=repo,
            generator=gen,
            max_attempts=1,
            evidence_dir=tmp_path / "evidence",
        )
    assert result is not None
    assert result["success"] is False
    assert result["lean_cert"]["atoms"][1]["z3_check_result"] == "unknown"


def test_ai_proof_generator_error_degrades_gracefully(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path)
    gen = ScriptedGenerator([])  # raises on first call
    with _patch_lake() as run:
        result = run_ai_proof_repair(
            cert=_cert(), mumei_lean_repo=repo, generator=gen, evidence_dir=tmp_path / "e"
        )
    assert result is not None
    assert result["success"] is False
    assert result["error_code"] == "generator_error"
    run.assert_not_called()


def test_ai_proof_noop_without_unknowns(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path)
    gen = ScriptedGenerator([])
    result = run_ai_proof_repair(
        cert={"atoms": [{"name": "ok", "z3_check_result": "unsat"}]},
        mumei_lean_repo=repo,
        generator=gen,
    )
    assert result is None
    assert gen.requests == []


def test_ai_proof_uses_escalation_bundle_hints(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path)
    gen = ScriptedGenerator([_good_module()])
    bundle = {
        "source_file": "x.mm",
        "loop_line": 3,
        "loop_context": {},
        "reason": "cegis_max_iterations_reached",
        "atom": {"name": "square_nonneg", "requires": "true"},
        "counterexamples": [{"x": -1}],
        "tried_invariants": [{"expression": "x >= 0", "iteration": 1}],
    }
    with _patch_lake(return_value=_lake_ok()):
        run_ai_proof_repair(
            cert=_cert(),
            mumei_lean_repo=repo,
            generator=gen,
            escalation_bundle=bundle,
            evidence_dir=tmp_path / "e",
        )
    hints = gen.requests[0]["escalation_bundle"]
    assert hints["counterexamples"] == [{"x": -1}]
    assert hints["tried_invariants"][0]["expression"] == "x >= 0"
    assert hints["atom"]["name"] == "square_nonneg"
    prompt = lean_ai_proof.render_ai_proof_prompt(gen.requests[0])
    assert "square_nonneg_correct" in prompt
    assert "x >= 0" in prompt


def test_ai_proof_refuses_duplicate_atom_names(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path)
    cert = _cert()
    cert["atoms"].append(
        {"name": "square_nonneg", "z3_check_result": "unknown", "ensures": "result > 0"}
    )
    gen = ScriptedGenerator([_good_module(), _good_module()])
    with _patch_lake(return_value=_lake_ok()) as lake:
        result = run_ai_proof_repair(cert=cert, mumei_lean_repo=repo, generator=gen)
    assert result is not None
    lake.assert_not_called()
    assert gen.requests == []
    assert result["success"] is False
    assert result["error_code"] == "ambiguous_atom_name"
    assert all(
        a["z3_check_result"] == "unknown"
        for a in result["lean_cert"]["atoms"]
        if a["name"] == "square_nonneg"
    )


# ---------------------------------------------------------------------------
# run_lean_bridge integration (Task 2-C stages first, then AI)
# ---------------------------------------------------------------------------


def test_run_lean_bridge_runs_ai_when_bridge_exits_zero_with_residual_unknown(
    tmp_path: Path,
) -> None:
    """`bridge.py` exits 0 for partial translations; residual unknowns still reach AI."""
    repo = _fake_repo(tmp_path)
    cert_path = tmp_path / "in.json"
    cert_path.write_text(json.dumps(_cert()), encoding="utf-8")
    lean_cert_out = tmp_path / "out.json"
    gen = ScriptedGenerator([_good_module()])

    def fake_bridge(*args, **kwargs):
        lean_cert_out.write_text(json.dumps(_cert()), encoding="utf-8")
        return MagicMock(returncode=0, stdout="partial translation", stderr="")

    with patch("agent.lean_bridge.subprocess.run", side_effect=fake_bridge), patch(
        "agent.lean_bridge.shutil.which", return_value="/usr/bin/lake"
    ), _patch_lake(return_value=_lake_ok()):
        result = lean_bridge.run_lean_bridge(
            cert_path=cert_path,
            lean_cert_out=lean_cert_out,
            mumei_lean_repo=repo,
            ai_proof_generator=gen,
            ai_proof_evidence_dir=tmp_path / "evidence",
        )

    assert len(gen.requests) == 1
    assert result["ai_proof_used"] is True
    atom = next(a for a in result["lean_cert"]["atoms"] if a["name"] == "square_nonneg")
    assert atom["z3_check_result"] == "lean_verified"
    on_disk = json.loads(lean_cert_out.read_text(encoding="utf-8"))
    disk_atom = next(a for a in on_disk["atoms"] if a["name"] == "square_nonneg")
    assert disk_atom["lean_metadata"]["ai_proof_used"] is True


def test_run_lean_bridge_ai_stage_after_known_witness(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path)
    (repo / "MumeiLean").mkdir()
    (repo / "MumeiLean" / "StdMathAbs.lean").write_text(
        "theorem abs_saturating_correct : True := by trivial\n", encoding="utf-8"
    )
    cert = _cert()
    cert["atoms"].append(
        {"name": "abs_saturating", "z3_check_result": "unknown"}
    )
    cert_path = tmp_path / "in.json"
    cert_path.write_text(json.dumps(cert), encoding="utf-8")
    gen = ScriptedGenerator([_good_module()])

    with patch("agent.lean_bridge.subprocess.run") as bridge_run, patch(
        "agent.lean_bridge.shutil.which", return_value="/usr/bin/lake"
    ), _patch_lake(return_value=_lake_ok()):
        bridge_run.side_effect = [
            MagicMock(returncode=1, stdout="", stderr="error: unsolved goals"),
            MagicMock(returncode=0, stdout="built", stderr=""),
        ]
        result = lean_bridge.run_lean_bridge(
            cert_path=cert_path,
            lean_cert_out=tmp_path / "out.json",
            mumei_lean_repo=repo,
            ai_proof_generator=gen,
            ai_proof_evidence_dir=tmp_path / "evidence",
        )

    assert result["success"] is True
    assert result["primary_error_code"] == "tactic_failed"
    assert result["fallback_strategy"] == AI_PROOF_STRATEGY
    assert result["ai_proof_used"] is True
    assert [s["name"] for s in result["strategy_attempts"]] == [
        "generated_bridge",
        "known_witness_module",
        AI_PROOF_STRATEGY,
    ]
    # AI stage only saw the residual atom, not the known witness one
    assert gen.requests[0]["atom"]["name"] == "square_nonneg"
    assert len(gen.requests) == 1
    atoms = {a["name"]: a for a in result["lean_cert"]["atoms"]}
    assert atoms["abs_saturating"]["lean_metadata"]["known_witness_used"] is True
    assert atoms["abs_saturating"]["lean_metadata"].get("ai_proof_used") is None
    assert atoms["square_nonneg"]["lean_metadata"]["ai_proof_used"] is True
    assert atoms["square_nonneg"]["lean_metadata"]["known_witness_used"] is False

    merged = lean_bridge.merge_lean_cert_into_proof_cert(cert, result["lean_cert"])
    assert lean_bridge.count_lean_verified_unknowns(cert, merged) == 2
    assert cert["atoms"][1]["z3_check_result"] == "unknown"  # non-mutating


def test_run_lean_bridge_ai_partial_success_reported(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path)
    cert = _cert()
    cert["atoms"].append(
        {"name": "hard_one", "z3_check_result": "unknown", "ensures": "false"}
    )
    cert_path = tmp_path / "in.json"
    cert_path.write_text(json.dumps(cert), encoding="utf-8")
    gen = ScriptedGenerator(
        [_good_module(), "theorem hard_one_correct : False := by sorry"]
    )

    with patch("agent.lean_bridge.subprocess.run") as bridge_run, patch(
        "agent.lean_bridge.shutil.which", return_value="/usr/bin/lake"
    ), _patch_lake(return_value=_lake_ok()):
        bridge_run.return_value = MagicMock(
            returncode=1, stdout="", stderr="error: unsolved goals"
        )
        result = lean_bridge.run_lean_bridge(
            cert_path=cert_path,
            lean_cert_out=tmp_path / "out.json",
            mumei_lean_repo=repo,
            ai_proof_generator=gen,
            ai_proof_max_attempts=1,
            ai_proof_evidence_dir=tmp_path / "evidence",
        )

    assert result["success"] is False
    assert result["partial_success"] is True
    assert result["ai_proof_used"] is True
    assert result["ai_proof_residual"] == ["hard_one"]
    atoms = {a["name"]: a for a in result["lean_cert"]["atoms"]}
    assert atoms["square_nonneg"]["z3_check_result"] == "lean_verified"
    assert atoms["hard_one"]["z3_check_result"] == "unknown"


def test_run_lean_bridge_without_generator_is_unchanged(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path)
    cert_path = tmp_path / "in.json"
    cert_path.write_text(json.dumps(_cert()), encoding="utf-8")

    with patch("agent.lean_bridge.subprocess.run") as bridge_run, patch(
        "agent.lean_bridge.shutil.which", return_value="/usr/bin/lake"
    ), patch("agent.lean_ai_proof.run_ai_proof_repair") as ai:
        bridge_run.return_value = MagicMock(
            returncode=1, stdout="", stderr="error: unsolved goals"
        )
        result = lean_bridge.run_lean_bridge(
            cert_path=cert_path,
            lean_cert_out=tmp_path / "out.json",
            mumei_lean_repo=repo,
        )

    ai.assert_not_called()
    assert result["success"] is False
    assert result["error_code"] == "tactic_failed"
    assert "ai_proof_used" not in result


# ---------------------------------------------------------------------------
# config gating: no-LLM / CI_FIXTURE_MODE skip
# ---------------------------------------------------------------------------


def test_lean_ai_proof_active_requires_flag_key_and_no_fixture_mode(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.delenv("CI_FIXTURE_MODE", raising=False)
    cfg = AgentConfig(api_key="k", enable_lean_ai_proof=True, ci_fixture_mode=False)
    assert cfg.lean_ai_proof_active() is True
    assert AgentConfig(api_key="", enable_lean_ai_proof=True).lean_ai_proof_active() is False
    assert AgentConfig(api_key="k", enable_lean_ai_proof=False).lean_ai_proof_active() is False
    assert (
        AgentConfig(api_key="k", enable_lean_ai_proof=True, ci_fixture_mode=True)
        .lean_ai_proof_active()
        is False
    )


def test_proliferate_generator_factory_respects_gating() -> None:
    from agent.proliferate import _lean_ai_proof_generator

    assert _lean_ai_proof_generator(AgentConfig(api_key="", enable_lean_ai_proof=True)) is None
    assert (
        _lean_ai_proof_generator(
            AgentConfig(api_key="k", enable_lean_ai_proof=True, ci_fixture_mode=True)
        )
        is None
    )
    gen = _lean_ai_proof_generator(
        AgentConfig(api_key="k", enable_lean_ai_proof=True, ci_fixture_mode=False)
    )
    assert isinstance(gen, lean_ai_proof.LLMAiProofGenerator)


def test_run_lean_fallback_inner_records_ai_provenance(tmp_path: Path) -> None:
    from agent.proliferate import _run_lean_fallback_inner

    repo = _fake_repo(tmp_path)
    results = [{"publish_result": {"proof_certificate": _cert()}}]
    gen = ScriptedGenerator([_good_module()])

    with patch("agent.lean_bridge.subprocess.run") as bridge_run, patch(
        "agent.lean_bridge.shutil.which", return_value="/usr/bin/lake"
    ), _patch_lake(return_value=_lake_ok()):
        bridge_run.return_value = MagicMock(
            returncode=1, stdout="", stderr="error: unsolved goals"
        )
        _run_lean_fallback_inner(
            results,
            mumei_lean_repo=str(repo),
            ai_proof_generator=gen,
            ai_proof_evidence_dir=str(tmp_path / "evidence"),
        )

    fallback = results[0]["lean_fallback"]
    assert fallback["proved"] == 1
    assert fallback["failed"] == 0
    assert fallback["success"] is True
    assert fallback["ai_proof_used"] is True
    assert fallback["ai_proof_residual"] == []
    assert fallback["fallback_strategy"] == AI_PROOF_STRATEGY
    upgraded = results[0]["publish_result"]["proof_certificate"]
    assert upgraded["atoms"][1]["z3_check_result"] == "lean_verified"
    assert upgraded["all_verified"] is True


def test_run_lean_fallback_inner_without_generator_has_no_ai_keys(tmp_path: Path) -> None:
    from agent.proliferate import _run_lean_fallback_inner

    repo = _fake_repo(tmp_path)
    results = [{"publish_result": {"proof_certificate": _cert()}}]

    with patch("agent.lean_bridge.subprocess.run") as bridge_run, patch(
        "agent.lean_bridge.shutil.which", return_value="/usr/bin/lake"
    ):
        bridge_run.return_value = MagicMock(
            returncode=1, stdout="", stderr="error: unsolved goals"
        )
        _run_lean_fallback_inner(results, mumei_lean_repo=str(repo))

    fallback = results[0]["lean_fallback"]
    assert fallback["proved"] == 0
    assert "ai_proof_used" not in fallback
    assert results[0]["publish_result"]["proof_certificate"]["atoms"][1][
        "z3_check_result"
    ] == "unknown"
