"""Task 2-D — AI Lean proof generation with a mocked LLM and mocked Lake."""
from __future__ import annotations

import json
import subprocess
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from agent import lean_ai_proof, lean_bridge
from agent.config import AgentConfig
from agent.lean_ai_proof import (
    AI_PROOF_STRATEGY,
    assemble_ai_module,
    extract_lean_source,
    extract_tactic_script,
    find_trusted_statement,
    reject_unsound_lean_source,
    run_ai_proof_repair,
)


class ScriptedGenerator:
    """Deterministic ``AiProofGenerator``: returns canned Lean per call."""

    def __init__(self, replies: list[str]) -> None:
        self.replies = list(replies)
        self.requests: list[dict] = []

    def generate_lean_proof(self, request: dict) -> str:
        self.requests.append(request)
        if not self.replies:
            raise RuntimeError("no scripted reply left")
        return self.replies.pop(0)


def _good_module(theorem: str = "square_nonneg_correct") -> str:
    """An LLM reply echoing the (fixed) statement plus a tactic script."""
    return (
        "```lean\n"
        f"theorem {theorem} (x : Int) (result : Int) (h_body : result = squareNonnegResult x) :\n"
        "    (True) → (result ≥ 0) := by\n"
        "  intro _\n  rw [h_body]\n  exact mul_self_nonneg x\n```"
    )


BRIDGE_MODULE = """import MumeiLean

/-!
# Generated.Ai_e2e

Auto-generated by `scripts/ingest_cert.py` for mumei module `ai_e2e`.
-/

namespace Generated.Ai_e2e

open MumeiLean

def squareNonnegResult (x : Int) : Int :=
  x * x

-- mumei_escalation_reason: z3_unknown_complex_fragment
/-- Auto-generated from mumei atom `square_nonneg`. -/
theorem square_nonneg_correct (x : Int) (result : Int) (h_body : result = squareNonnegResult x) :
    (True) → (result ≥ 0) := by
  rw [h_body]
  unfold squareNonnegResult
  mumei_arith_deep

theorem other_correct : True := by
  sorry

end Generated.Ai_e2e
"""


# Stand-in for mumei-lean's translator: emits BRIDGE_MODULE for the atoms of
# the certificate it is handed (so the regenerated statement follows the cert,
# not whatever is lying around in ``generated/``).
INGEST_STUB = f'''import json, sys
from pathlib import Path
cert = json.loads(Path(sys.argv[1]).read_text())
out = Path(sys.argv[sys.argv.index("--out") + 1])
names = [a["name"] for a in cert["atoms"] if a.get("z3_check_result") == "unknown"]
if "square_nonneg" not in names:
    sys.exit(0)
module = out / "Generated" / "Ai_e2e.lean"
module.parent.mkdir(parents=True, exist_ok=True)
module.write_text({BRIDGE_MODULE!r})
'''


def _fake_repo(
    tmp_path: Path, *, with_statement: bool = True, with_ingest: bool = True
) -> Path:
    repo = tmp_path / "mumei-lean"
    (repo / "scripts").mkdir(parents=True)
    (repo / "scripts" / "bridge.py").write_text("# stub\n")
    if with_ingest:
        (repo / "scripts" / "ingest_cert.py").write_text(INGEST_STUB, encoding="utf-8")
    (repo / "scripts" / "export_cert.py").write_text(
        'TRANSLATOR_VERSION = "mumei-lean-translator-ir-v1"\n'
        'BRIDGE_LEMMA_HASH = "hash-for-test"\n',
        encoding="utf-8",
    )
    (repo / "lakefile.lean").write_text("-- stub\n")
    if with_statement:
        generated = repo / "generated" / "Generated"
        generated.mkdir(parents=True)
        (generated / "Ai_e2e.lean").write_text(BRIDGE_MODULE, encoding="utf-8")
    return repo


def _cert() -> dict:
    return {
        "file": "ai_e2e.mm",
        "all_verified": False,
        "atoms": [
            {"name": "ok", "z3_check_result": "unsat"},
            {
                "name": "square_nonneg",
                "z3_check_result": "unknown",
                "z3_result_class": "unknown",
                "escalation_reason": "z3_unknown_complex_fragment",
                "requires": "true",
                "ensures": "result >= 0",
                "body_expr": "x * x",
            },
        ],
    }


BRIDGE_LEAN_MODULE = "Generated.Ai_e2e"


def _axioms_ok(repo_path, *, lean_module, qualified_theorem, timeout):
    return 0, (
        f"'{qualified_theorem}' depends on axioms: "
        "[propext, Classical.choice, Quot.sound]\n"
    )


class FakeBridge:
    """Stand-in for ``scripts/bridge.py --external-proofs``.

    ``steps`` gives one verdict per bridge round (``"ok"`` / ``"unsolved"`` /
    ``"type_mismatch"`` / ``"import_error"`` / ``"sorry_warning"`` /
    ``"silent"``), either as a string for every submitted atom or a
    ``{atom: verdict}`` dict.  The last step repeats.  Writes the exported
    ``.lean-cert.json`` and the B-3 failure report exactly like the bridge:
    verified atoms carry ``ai_proof_used`` + ``external_proof`` provenance,
    failed atoms stay ``unknown`` and get a per-atom failure entry.
    """

    def __init__(self, steps: list) -> None:
        self.steps = list(steps) or ["ok"]
        self.calls: list[dict] = []

    def __call__(
        self,
        repo_path,
        *,
        cert_path,
        external_proofs_path,
        lean_cert_out,
        failure_report_path,
        summary_path,
        timeout,
    ):
        cert = json.loads(Path(cert_path).read_text(encoding="utf-8"))
        payload = json.loads(Path(external_proofs_path).read_text(encoding="utf-8"))
        proofs = payload["proofs"]
        step = self.steps[min(len(self.calls), len(self.steps) - 1)]
        self.calls.append({"cert": cert, "proofs": proofs, "timeout": timeout})
        verdicts = {
            p["atom"]: (step if isinstance(step, str) else step.get(p["atom"], "ok"))
            for p in proofs
        }
        lean_cert = json.loads(json.dumps(cert))
        failures = []
        for atom in lean_cert["atoms"]:
            verdict = verdicts.get(atom["name"])
            if verdict is None:
                continue
            theorem = f"{atom['name']}_correct"
            if verdict == "ok":
                atom["z3_check_result"] = "lean_verified"
                atom["status"] = "verified"
                atom["translator_version"] = "mumei-lean-translator-ir-v1"
                atom["bridge_lemma_hash"] = "hash-for-test"
                atom["lean_metadata"] = {
                    "status": "lean_verified",
                    "theorem_name": theorem,
                    "lean_module": BRIDGE_LEAN_MODULE,
                    "lean_theorem_name": f"{BRIDGE_LEAN_MODULE}.{theorem}",
                    "translator_version": "mumei-lean-translator-ir-v1",
                    "bridge_lemma_hash": "hash-for-test",
                    "proof_path": "generated/Generated/Ai_e2e.lean",
                    "known_witness_used": False,
                    "ai_proof_used": True,
                    "ai_proof_attempts": next(
                        p["attempts"] for p in proofs if p["atom"] == atom["name"]
                    ),
                    "external_proof": {"source": "ai_generated_proof"},
                    "diagnostics": ["external_proof_source=ai_generated_proof"],
                }
                continue
            kind, message = {
                "unsolved": ("unsolved_goals", "unsolved goals\nx : Int\n⊢ 0 ≤ x * x"),
                "type_mismatch": ("type_mismatch", "type mismatch\n  h\nhas type"),
                "import_error": ("import_error", "unknown module prefix 'Mathlib.Nope'"),
                "sorry_warning": ("sorry", "declaration uses 'sorry'"),
                "silent": (None, None),
            }[verdict]
            if kind is not None:
                failures.append(
                    {
                        "atom": atom["name"],
                        "file": f"{repo_path}/generated/Generated/Ai_e2e.lean",
                        "line": 12,
                        "column": 2,
                        "kind": kind,
                        "message": message,
                    }
                )
        Path(lean_cert_out).write_text(json.dumps(lean_cert), encoding="utf-8")
        Path(failure_report_path).write_text(
            json.dumps(
                {"schema": "mumei-lean-build-failures-v1", "failures": failures, "unattributed": []}
            ),
            encoding="utf-8",
        )
        Path(summary_path).write_text("{}", encoding="utf-8")
        rc = 0 if all(v in {"ok", "sorry_warning", "silent"} for v in verdicts.values()) else 1
        log = "Build completed successfully." if rc == 0 else "error: " + "\n".join(
            f["message"] for f in failures
        )
        return rc, log


def _patch_bridge(bridge: FakeBridge | None = None, **kwargs):
    """Patch the AI stage's canonical bridge runner (``(returncode, log)``)."""
    if bridge is not None:
        return patch("agent.lean_ai_proof._bridge_check_external_proofs", side_effect=bridge)
    return patch("agent.lean_ai_proof._bridge_check_external_proofs", **kwargs)


_REAL_SUBPROCESS_RUN = subprocess.run


@pytest.fixture(autouse=True)
def _lake_on_path() -> None:
    # ``shutil`` / ``subprocess`` are shared module objects for lean_bridge /
    # lean_ai_proof; tests below patch ``subprocess.run`` to fake bridge.py,
    # so the translator stub keeps running through the real one.
    with patch(
        "agent.lean_ai_proof.shutil.which", return_value="/usr/bin/lake"
    ), patch(
        "agent.lean_ai_proof._print_axioms", side_effect=_axioms_ok
    ), patch(
        "agent.lean_ai_proof._run_translator",
        side_effect=lambda cmd, *, cwd, timeout: _REAL_SUBPROCESS_RUN(
            cmd, cwd=cwd, capture_output=True, text=True, timeout=timeout, check=False
        ),
    ):
        yield


# ---------------------------------------------------------------------------
# source hygiene
# ---------------------------------------------------------------------------


def test_extract_lean_source_strips_fences() -> None:
    assert extract_lean_source("```lean\ntheorem t : True := trivial\n```") == (
        "theorem t : True := trivial"
    )
    assert extract_lean_source("theorem t : True := trivial") == (
        "theorem t : True := trivial"
    )


@pytest.mark.parametrize(
    "source, expected",
    [
        ("sorry", "forbidden_token:sorry"),
        ("admit", "forbidden_token:admit"),
        ("exact bad\naxiom bad : False", "forbidden_token:axiom"),
        ("native_decide", "forbidden_token:native_decide"),
        ("run_tac do pure ()", "forbidden_token:run_tac"),
        ("set_option maxHeartbeats 0 in\n  simp", "forbidden_token:set_option"),
        ("trivial\ntheorem other : True := trivial", "forbidden_token:declaration"),
        ("", "empty_source"),
        ("intro _\nexact mul_self_nonneg x", None),
    ],
)
def test_reject_unsound_lean_source(source: str, expected: str | None) -> None:
    assert reject_unsound_lean_source(source, "t_correct") == expected


def test_extract_tactic_script_accepts_full_theorem_or_bare_tactics() -> None:
    assert extract_tactic_script(_good_module(), "square_nonneg_correct") == (
        "intro _\nrw [h_body]\nexact mul_self_nonneg x"
    )
    assert extract_tactic_script("```lean\n  simp\n  ring\n```", "t") == "simp\nring"
    assert extract_tactic_script("by\n  omega", "t") == "omega"
    # a *different* statement for the expected name is discarded: only the
    # tactic text survives, and it is spliced under the trusted header.
    assert extract_tactic_script(
        "theorem t_correct : True := by\n  trivial", "t_correct"
    ) == "trivial"


def test_trusted_statement_is_lifted_from_bridge_module(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path)
    stmt = find_trusted_statement(repo, "square_nonneg", theorem_name="square_nonneg_correct")
    assert stmt is not None
    assert stmt.namespace == "Generated.Ai_e2e"
    assert stmt.header.startswith("theorem square_nonneg_correct (x : Int) (result : Int)")
    assert stmt.header.endswith("(True) → (result ≥ 0)")
    assert "def squareNonnegResult" in stmt.preamble
    assert "other_correct" not in stmt.preamble
    assert "mumei_arith_deep" not in stmt.preamble
    module = assemble_ai_module(
        stmt, module="Generated.AiProof.Square_nonneg", tactics="trivial", nonce="n"
    )
    assert "namespace Generated.AiProof.Square_nonneg" in module
    assert module.rstrip().endswith("end Generated.AiProof.Square_nonneg")
    assert f"{stmt.header} := by\n  trivial" in module
    assert "#print axioms square_nonneg_correct" in module
    assert "sorry" not in module
    assert find_trusted_statement(repo, "nope", theorem_name="nope_correct") is None


def test_ai_proof_skips_atoms_without_trusted_statement(tmp_path: Path) -> None:
    """Translator emitted no statement for the atom (partial_translation)."""
    repo = _fake_repo(tmp_path, with_statement=False)
    (repo / "scripts" / "ingest_cert.py").write_text("", encoding="utf-8")
    gen = ScriptedGenerator([_good_module()])
    with _patch_bridge() as bridge:
        result = run_ai_proof_repair(cert=_cert(), mumei_lean_repo=repo, generator=gen)
    assert result is not None
    assert gen.requests == []
    bridge.assert_not_called()
    assert result["success"] is False
    assert result["error_code"] == "no_trusted_statement"
    assert result["ai_proof_residual"] == ["square_nonneg"]


def test_ai_proof_wrong_statement_cannot_certify_contract(tmp_path: Path) -> None:
    """`theorem square_nonneg_correct : True := by trivial` must not promote."""
    repo = _fake_repo(tmp_path)
    gen = ScriptedGenerator(["theorem square_nonneg_correct : True := by\n  trivial"])
    bridge = FakeBridge(["unsolved"])

    with _patch_bridge(bridge):
        result = run_ai_proof_repair(
            cert=_cert(), mumei_lean_repo=repo, generator=gen, max_attempts=1
        )
    assert result is not None and result["success"] is False
    assert len(bridge.calls) == 1
    # only the tactic script reaches the bridge; the statement is regenerated
    # by the bridge from the certificate it is handed, never taken from the model
    [proof] = bridge.calls[0]["proofs"]
    assert proof == {
        "atom": "square_nonneg",
        "tactic_script": "trivial",
        "module_key": "ai_e2e",
        "source": "ai_generated_proof",
        "attempts": 1,
    }
    assert bridge.calls[0]["cert"]["atoms"][1]["ensures"] == "result >= 0"
    assert result["lean_cert"]["atoms"][1]["z3_check_result"] == "unknown"


@pytest.mark.parametrize(
    "log, expected",
    [
        ("'X.t_correct' depends on axioms: [propext, sorryAx]", "unsound_axioms"),
        ("'X.t_correct' depends on axioms: [myAxiom]", "unsound_axioms"),
        ("'X.t_correct' depends on axioms: [propext, Classical.choice, Quot.sound]", None),
        ("'X.t_correct' does not depend on any axioms", None),
        ("Build completed successfully.", "axiom_audit_missing"),
    ],
)
def test_axiom_audit(log: str, expected: str | None) -> None:
    assert lean_ai_proof._audit_axioms(log, "t_correct") == expected


def test_axiom_audit_requires_exact_declaration() -> None:
    log = "'Generated.Other.t_correct' depends on axioms: [propext]"
    assert (
        lean_ai_proof._audit_axioms(log, "t_correct", module="Generated.AiProof.T_abc")
        == "axiom_audit_missing"
    )
    assert (
        lean_ai_proof._audit_axioms(
            "'X.not_t_correct' does not depend on any axioms", "t_correct"
        )
        == "axiom_audit_missing"
    )
    assert (
        lean_ai_proof._audit_axioms(
            "'Generated.AiProof.T_abc.t_correct' depends on axioms: [propext]",
            "t_correct",
            module="Generated.AiProof.T_abc",
        )
        is None
    )


def test_bridge_timeout_is_classified(tmp_path: Path) -> None:
    def timed_out(*args, **kwargs):
        raise subprocess.TimeoutExpired(cmd="bridge.py", timeout=5)

    with patch("agent.lean_ai_proof.subprocess.run", side_effect=timed_out):
        rc, log = lean_ai_proof._bridge_check_external_proofs(
            tmp_path,
            cert_path=tmp_path / "c.json",
            external_proofs_path=tmp_path / "p.json",
            lean_cert_out=tmp_path / "o.json",
            failure_report_path=tmp_path / "f.json",
            summary_path=tmp_path / "s.json",
            timeout=5,
        )
    assert rc == -1
    assert "bridge.py timed out" in log


def test_bridge_is_invoked_with_canonical_flags(tmp_path: Path) -> None:
    with patch("agent.lean_ai_proof.subprocess.run") as run:
        run.return_value = MagicMock(returncode=0, stdout="ok", stderr="")
        rc, log = lean_ai_proof._bridge_check_external_proofs(
            tmp_path,
            cert_path=tmp_path / "c.json",
            external_proofs_path=tmp_path / "p.json",
            lean_cert_out=tmp_path / "o.json",
            failure_report_path=tmp_path / "f.json",
            summary_path=tmp_path / "s.json",
            timeout=5,
        )
    assert rc == 0 and "ok" in log
    cmd = run.call_args.args[0]
    assert cmd[1] == str(tmp_path / "scripts" / "bridge.py")
    assert cmd[cmd.index("--cert") + 1] == str(tmp_path / "c.json")
    assert cmd[cmd.index("--external-proofs") + 1] == str(tmp_path / "p.json")
    assert cmd[cmd.index("--failure-report") + 1] == str(tmp_path / "f.json")
    assert cmd[cmd.index("--lean-cert-out") + 1] == str(tmp_path / "o.json")
    assert run.call_args.kwargs["cwd"] == str(tmp_path)


def test_ai_proof_evidence_is_not_overwritten_across_runs(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path)
    evidence = tmp_path / "evidence"
    paths = []
    for reply in (_good_module(), "```lean\n  intro _\n  omega\n```"):
        with _patch_bridge(FakeBridge(["ok"])):
            result = run_ai_proof_repair(
                cert=_cert(),
                mumei_lean_repo=repo,
                generator=ScriptedGenerator([reply]),
                evidence_dir=evidence,
            )
        assert result is not None
        atom = next(a for a in result["lean_cert"]["atoms"] if a["name"] == "square_nonneg")
        paths.append(Path(atom["lean_metadata"]["ai_proof_evidence"]["tactic_path"]))
    assert paths[0] != paths[1]
    assert "mul_self_nonneg" in paths[0].read_text()
    assert "omega" in paths[1].read_text()


# ---------------------------------------------------------------------------
# run_ai_proof_repair
# ---------------------------------------------------------------------------


def test_ai_proof_promotes_only_after_lake_success(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path)
    gen = ScriptedGenerator([_good_module()])
    evidence = tmp_path / "evidence"

    bridge = FakeBridge(["ok"])
    with _patch_bridge(bridge), patch(
        "agent.lean_ai_proof._print_axioms", side_effect=_axioms_ok
    ) as audit:
        result = run_ai_proof_repair(
            cert=_cert(),
            mumei_lean_repo=repo,
            generator=gen,
            evidence_dir=evidence,
        )

    assert result is not None
    assert result["success"] is True
    assert result["ai_proof_used"] is True
    assert result["ai_proof_proved"] == 1
    assert result["fallback_strategy"] == AI_PROOF_STRATEGY
    assert len(bridge.calls) == 1
    assert bridge.calls[0]["proofs"][0]["tactic_script"] == (
        "intro _\nrw [h_body]\nexact mul_self_nonneg x"
    )
    # #print axioms is probed on the theorem the bridge actually built
    assert audit.call_args.kwargs["lean_module"] == BRIDGE_LEAN_MODULE
    assert audit.call_args.kwargs["qualified_theorem"] == (
        f"{BRIDGE_LEAN_MODULE}.square_nonneg_correct"
    )

    atom = next(a for a in result["lean_cert"]["atoms"] if a["name"] == "square_nonneg")
    assert atom["z3_check_result"] == "lean_verified"
    assert atom["lean_fallback_strategy"] == AI_PROOF_STRATEGY
    meta = atom["lean_metadata"]
    assert meta["ai_proof_used"] is True
    assert meta["known_witness_used"] is False
    assert meta["ai_proof_attempts"] == 1
    assert meta["lean_module"] == BRIDGE_LEAN_MODULE
    assert meta["theorem_name"] == "square_nonneg_correct"
    assert meta["external_proof"]["source"] == AI_PROOF_STRATEGY
    assert atom["translator_version"] == "mumei-lean-translator-ir-v1"
    assert atom["bridge_lemma_hash"] == "hash-for-test"
    assert atom["lean_result_metadata"]["ai_proof_used"] is True
    # evidence: tactic source, bridge log and axiom audit persisted
    evidence_meta = meta["ai_proof_evidence"]
    assert Path(evidence_meta["tactic_path"]).read_text(encoding="utf-8").startswith(
        "import MumeiLean"
    )
    assert "Build completed" in Path(evidence_meta["build_log_path"]).read_text(
        encoding="utf-8"
    )
    assert "depends on axioms" in Path(evidence_meta["axiom_audit_log_path"]).read_text(
        encoding="utf-8"
    )
    assert (evidence / result["evidence_dir"].split("/")[-1] / "round_1" / "external_proofs.json").is_file()
    assert not list(repo.glob(".ai_proof_axioms_*.lean"))
    # unaffected atoms untouched
    assert next(a for a in result["lean_cert"]["atoms"] if a["name"] == "ok") == {
        "name": "ok",
        "z3_check_result": "unsat",
    }


def test_ai_proof_repairs_with_lean_feedback(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path)
    gen = ScriptedGenerator([_good_module(), _good_module()])

    bridge = FakeBridge(["unsolved", "ok"])

    with _patch_bridge(bridge):
        result = run_ai_proof_repair(
            cert=_cert(),
            mumei_lean_repo=repo,
            generator=gen,
            max_attempts=3,
            evidence_dir=tmp_path / "evidence",
        )

    assert result is not None and result["success"] is True
    assert len(gen.requests) == 2
    assert len(bridge.calls) == 2
    assert bridge.calls[1]["proofs"][0]["attempts"] == 2
    assert gen.requests[0]["feedback"] == []
    feedback = gen.requests[1]["feedback"]
    assert feedback[0]["error_code"] == "tactic_failed"
    # B-3 structured per-atom failure is what the model is repaired with
    [failure] = feedback[0]["failures"]
    assert failure["kind"] == "unsolved_goals"
    assert failure["line"] == 12
    assert "⊢ 0 ≤ x * x" in failure["message"]
    prompt = lean_ai_proof.render_ai_proof_prompt(gen.requests[1])
    assert "unsolved_goals (line 12)" in prompt
    outcome = result["ai_proof_outcomes"][0]
    assert outcome["attempts"] == 2
    assert [a["accepted"] for a in outcome["attempt_log"]] == [False, True]
    atom = result["lean_cert"]["atoms"][1]
    assert atom["lean_metadata"]["ai_proof_attempts"] == 2


def test_ai_proof_keeps_unknown_when_all_attempts_fail(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path)
    gen = ScriptedGenerator([_good_module()] * 2)

    with _patch_bridge(FakeBridge(["unsolved"])):
        result = run_ai_proof_repair(
            cert=_cert(),
            mumei_lean_repo=repo,
            generator=gen,
            max_attempts=2,
            evidence_dir=tmp_path / "evidence",
        )

    assert result is not None
    assert result["success"] is False
    assert result["ai_proof_used"] is False
    assert result["error_code"] == "tactic_failed"
    assert result["ai_proof_residual"] == ["square_nonneg"]
    assert result["lean_cert"]["atoms"][1]["z3_check_result"] == "unknown"
    assert "lean_metadata" not in result["lean_cert"]["atoms"][1]
    assert len(gen.requests) == 2


def test_ai_proof_rejects_sorry_before_lake(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path)
    gen = ScriptedGenerator(
        ["theorem square_nonneg_correct : True := by sorry", _good_module()]
    )

    bridge = FakeBridge(["ok"])
    with _patch_bridge(bridge):
        result = run_ai_proof_repair(
            cert=_cert(),
            mumei_lean_repo=repo,
            generator=gen,
            evidence_dir=tmp_path / "evidence",
        )

    assert result is not None and result["success"] is True
    assert len(bridge.calls) == 1  # the sorry attempt never reached the bridge
    assert bridge.calls[0]["proofs"][0]["attempts"] == 2
    assert gen.requests[1]["feedback"][0]["rejection_reason"] == "forbidden_token:sorry"
    log = result["ai_proof_outcomes"][0]["attempt_log"]
    assert log[0]["error_code"] == "unsound_source"


def test_ai_proof_does_not_trust_exit_zero_with_sorry_warning(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path)
    gen = ScriptedGenerator([_good_module()])
    with _patch_bridge(FakeBridge(["sorry_warning"])):
        result = run_ai_proof_repair(
            cert=_cert(),
            mumei_lean_repo=repo,
            generator=gen,
            max_attempts=1,
            evidence_dir=tmp_path / "evidence",
        )
    assert result is not None
    assert result["success"] is False
    assert result["error_code"] == "tactic_failed"
    assert result["lean_cert"]["atoms"][1]["z3_check_result"] == "unknown"


def test_ai_proof_bridge_exit_zero_without_promotion_is_not_trusted(tmp_path: Path) -> None:
    """bridge.py exiting 0 (partial translation) while the atom stays unknown."""
    repo = _fake_repo(tmp_path)
    gen = ScriptedGenerator([_good_module()])
    with _patch_bridge(FakeBridge(["silent"])):
        result = run_ai_proof_repair(
            cert=_cert(), mumei_lean_repo=repo, generator=gen, max_attempts=1
        )
    assert result is not None
    assert result["success"] is False
    assert result["ai_proof_used"] is False
    assert result["lean_cert"]["atoms"][1]["z3_check_result"] == "unknown"


def test_ai_proof_lean_verified_without_ai_provenance_is_not_promoted(tmp_path: Path) -> None:
    """An exported atom that lacks ``ai_proof_used`` is not attributed to the AI stage."""
    repo = _fake_repo(tmp_path)
    gen = ScriptedGenerator([_good_module()])
    inner = FakeBridge(["ok"])

    def strip_provenance(repo_path, **kwargs):
        rc, log = inner(repo_path, **kwargs)
        cert = json.loads(Path(kwargs["lean_cert_out"]).read_text(encoding="utf-8"))
        for atom in cert["atoms"]:
            meta = atom.get("lean_metadata")
            if meta:
                meta.pop("ai_proof_used", None)
                meta.pop("external_proof", None)
        Path(kwargs["lean_cert_out"]).write_text(json.dumps(cert), encoding="utf-8")
        return rc, log

    with _patch_bridge(side_effect=strip_provenance), patch(
        "agent.lean_ai_proof._print_axioms", side_effect=_axioms_ok
    ) as audit:
        result = run_ai_proof_repair(
            cert=_cert(), mumei_lean_repo=repo, generator=gen, max_attempts=1
        )
    assert result is not None
    assert result["success"] is False
    audit.assert_not_called()
    assert result["lean_cert"]["atoms"][1]["z3_check_result"] == "unknown"


def test_ai_proof_axiom_audit_blocks_promotion(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path)
    gen = ScriptedGenerator([_good_module()])

    def bad_axioms(repo_path, *, lean_module, qualified_theorem, timeout):
        return 0, f"'{qualified_theorem}' depends on axioms: [propext, sorryAx]\n"

    with _patch_bridge(FakeBridge(["ok"])), patch(
        "agent.lean_ai_proof._print_axioms", side_effect=bad_axioms
    ):
        result = run_ai_proof_repair(
            cert=_cert(), mumei_lean_repo=repo, generator=gen, max_attempts=1
        )
    assert result is not None
    assert result["success"] is False
    assert result["error_code"] == "unsound_axioms"
    assert result["lean_cert"]["atoms"][1]["z3_check_result"] == "unknown"


def test_ai_proof_import_error_feedback_is_structured(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path)
    gen = ScriptedGenerator([_good_module(), _good_module(), _good_module()])
    with _patch_bridge(FakeBridge(["import_error", "type_mismatch", "ok"])):
        result = run_ai_proof_repair(
            cert=_cert(), mumei_lean_repo=repo, generator=gen, max_attempts=3
        )
    assert result is not None and result["success"] is True
    kinds = [req["feedback"][-1]["failures"][0]["kind"] for req in gen.requests[1:]]
    assert kinds == ["import_error", "type_mismatch"]
    codes = [a["error_code"] for a in result["ai_proof_outcomes"][0]["attempt_log"]]
    assert codes == ["import_error", "tactic_failed", None]


def test_ai_proof_generator_error_degrades_gracefully(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path)
    gen = ScriptedGenerator([])  # raises on every call
    with _patch_bridge() as bridge:
        result = run_ai_proof_repair(
            cert=_cert(), mumei_lean_repo=repo, generator=gen, evidence_dir=tmp_path / "e"
        )
    assert result is not None
    assert result["success"] is False
    assert result["error_code"] == "generator_error"
    bridge.assert_not_called()


def test_ai_proof_transient_generator_error_is_retried(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path)

    class Flaky(ScriptedGenerator):
        def __init__(self) -> None:
            super().__init__([_good_module()])
            self.calls = 0

        def generate_lean_proof(self, request: dict) -> str:
            self.calls += 1
            if self.calls == 1:
                raise RuntimeError("HTTP 429")
            return super().generate_lean_proof(request)

    gen = Flaky()
    with _patch_bridge(FakeBridge(["ok"])):
        result = run_ai_proof_repair(
            cert=_cert(), mumei_lean_repo=repo, generator=gen, max_attempts=2
        )
    assert result is not None
    assert gen.calls == 2
    assert result["success"] is True
    assert gen.requests[0]["feedback"][0]["error_code"] == "generator_error"


def test_ai_proof_zero_attempts_does_nothing(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path)
    gen = ScriptedGenerator([_good_module()])
    with _patch_bridge() as bridge:
        result = run_ai_proof_repair(
            cert=_cert(), mumei_lean_repo=repo, generator=gen, max_attempts=0
        )
    assert result is None
    assert gen.requests == []
    bridge.assert_not_called()


def test_ai_proof_bridge_receives_the_repaired_certificate(tmp_path: Path) -> None:
    """The bridge regenerates statements from the exact certificate being repaired."""
    repo = _fake_repo(tmp_path)
    gen = ScriptedGenerator([_good_module()])
    bridge = FakeBridge(["ok"])
    cert = _cert()
    with _patch_bridge(bridge):
        result = run_ai_proof_repair(
            cert=cert, mumei_lean_repo=repo, generator=gen, max_attempts=1
        )
    assert result is not None and result["success"] is True
    assert bridge.calls[0]["cert"] == cert
    assert cert["atoms"][1]["z3_check_result"] == "unknown"  # non-mutating


def test_ai_proof_evidence_is_isolated_per_run(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path)
    dirs = []
    for _ in range(2):
        with _patch_bridge(FakeBridge(["ok"])):
            result = run_ai_proof_repair(
                cert=_cert(), mumei_lean_repo=repo, generator=ScriptedGenerator([_good_module()])
            )
        assert result is not None
        dirs.append(result["evidence_dir"])
    assert dirs[0] != dirs[1]
    assert all((Path(d) / "round_1" / "external_proofs.json").is_file() for d in dirs)


def test_ai_proof_feedback_redacts_local_paths(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path)
    gen = ScriptedGenerator([_good_module(), _good_module()])
    with _patch_bridge(FakeBridge(["unsolved"])):
        run_ai_proof_repair(
            cert=_cert(), mumei_lean_repo=repo, generator=gen, max_attempts=2
        )
    feedback = gen.requests[1]["feedback"][0]
    assert str(repo.resolve()) not in json.dumps(feedback)
    assert feedback["failures"][0]["file"] == "<mumei-lean>/generated/Generated/Ai_e2e.lean"


def test_trusted_statement_is_scoped_to_atom_module(tmp_path: Path) -> None:
    """A same-named theorem in another generated module must never be used."""
    repo = _fake_repo(tmp_path)
    stale = BRIDGE_MODULE.replace("Generated.Ai_e2e", "Generated.Stale").replace(
        "(result ≥ 0)", "(result ≥ 1)"
    )
    (repo / "generated" / "Generated" / "Stale.lean").write_text(stale, encoding="utf-8")

    scoped = find_trusted_statement(
        repo, "square_nonneg", theorem_name="square_nonneg_correct", module_key="ai_e2e"
    )
    assert scoped is not None
    assert scoped.source_path.endswith("Ai_e2e.lean")
    assert "(result ≥ 0)" in scoped.header
    # unscoped lookup is ambiguous → refuse rather than guess
    assert (
        find_trusted_statement(repo, "square_nonneg", theorem_name="square_nonneg_correct")
        is None
    )
    assert (
        find_trusted_statement(
            repo, "square_nonneg", theorem_name="square_nonneg_correct", module_key="other"
        )
        is None
    )

    # end-to-end: the cert's file-derived module key selects the right statement
    cert = _cert()
    gen = ScriptedGenerator([_good_module()])
    with _patch_bridge(FakeBridge(["ok"])):
        result = run_ai_proof_repair(cert=cert, mumei_lean_repo=repo, generator=gen)
    assert result is not None and result["success"] is True
    header = gen.requests[0]["statement"]["header"]
    assert "(result ≥ 0)" in header and "(result ≥ 1)" not in header
    assert gen.requests[0]["statement"]["source_path"].endswith("Ai_e2e.lean")
    assert "_statements" in gen.requests[0]["statement"]["source_path"]


def test_bridge_module_path_mirrors_ingest_cert(tmp_path: Path) -> None:
    assert lean_ai_proof.bridge_module_path_for(tmp_path, "std/math/abs") == (
        tmp_path / "generated" / "Generated" / "Std" / "Math" / "Abs.lean"
    )
    assert lean_ai_proof.bridge_module_key_for({"file": "./ai_e2e.mm"}, {}) == "ai_e2e"
    assert lean_ai_proof.bridge_module_key_for({}, {"module_key": "std/core"}) == "std/core"
    assert lean_ai_proof.bridge_module_key_for({}, {}) == "atom_module"


def test_stale_generated_module_never_supplies_the_statement(tmp_path: Path) -> None:
    """Bridge failed before rewriting generated/Generated/Ai_e2e.lean: the file
    still holds a same-named theorem with an *older* contract.  The AI stage
    must prove the statement regenerated from the current certificate instead."""
    repo = _fake_repo(tmp_path, with_statement=False)
    stale_dir = repo / "generated" / "Generated"
    stale_dir.mkdir(parents=True)
    stale = BRIDGE_MODULE.replace("(True) → (result ≥ 0)", "(True) → (True)")
    (stale_dir / "Ai_e2e.lean").write_text(stale, encoding="utf-8")
    gen = ScriptedGenerator([_good_module()])

    with _patch_bridge(FakeBridge(["ok"])):
        result = run_ai_proof_repair(
            cert=_cert(),
            mumei_lean_repo=repo,
            generator=gen,
            evidence_dir=tmp_path / "e",
        )
    assert result is not None and result["success"] is True
    assert "(True) → (result ≥ 0)" in gen.requests[0]["statement"]["header"]
    assert "(True) → (True)" not in gen.requests[0]["statement"]["header"]
    meta = result["lean_cert"]["atoms"][1]["lean_metadata"]
    statement_path = meta["ai_proof_evidence"]["statement_source_path"]
    assert "_statements" in statement_path
    assert Path(statement_path).is_file()
    assert "(True) → (result ≥ 0)" in Path(statement_path).read_text(encoding="utf-8")


def test_ai_proof_fails_closed_without_translator(tmp_path: Path) -> None:
    """No scripts/ingest_cert.py → the checkout's generated module (possibly
    stale) is *not* used as a fallback; every atom stays unknown."""
    repo = _fake_repo(tmp_path, with_ingest=False)
    gen = ScriptedGenerator([_good_module()])
    with _patch_bridge() as bridge:
        result = run_ai_proof_repair(cert=_cert(), mumei_lean_repo=repo, generator=gen)
    assert result is not None
    bridge.assert_not_called()
    assert gen.requests == []
    assert result["success"] is False
    assert result["error_code"] == "no_trusted_statement"
    assert any("ingest_cert.py" in d for d in result["diagnostics"])
    assert result["lean_cert"]["atoms"][1]["z3_check_result"] == "unknown"


def test_ai_proof_fails_closed_when_translator_errors(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path)
    (repo / "scripts" / "ingest_cert.py").write_text("import sys\nsys.exit(3)\n")
    gen = ScriptedGenerator([_good_module()])
    with _patch_bridge() as bridge:
        result = run_ai_proof_repair(cert=_cert(), mumei_lean_repo=repo, generator=gen)
    assert result is not None
    bridge.assert_not_called()
    assert result["error_code"] == "no_trusted_statement"


def test_evidence_dirs_are_distinct_for_case_variant_atoms(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path)
    two_theorems = BRIDGE_MODULE.replace(
        "theorem other_correct : True := by\n  sorry\n",
        "theorem Square_nonneg_correct (x : Int) (result : Int) "
        "(h_body : result = squareNonnegResult x) :\n"
        "    (True) → (result ≥ 0) := by\n  sorry\n",
    )
    (repo / "scripts" / "ingest_cert.py").write_text(
        INGEST_STUB.replace(repr(BRIDGE_MODULE), repr(two_theorems)),
        encoding="utf-8",
    )
    cert = _cert()
    cert["atoms"].append(dict(cert["atoms"][1], name="Square_nonneg"))
    gen = ScriptedGenerator(
        [_good_module(), _good_module("Square_nonneg_correct")]
    )

    bridge = FakeBridge(["ok"])
    with _patch_bridge(bridge):
        result = run_ai_proof_repair(
            cert=cert, mumei_lean_repo=repo, generator=gen, evidence_dir=tmp_path / "e"
        )
    assert result is not None and result["success"] is True
    # both atoms travel in one bridge round
    assert sorted(p["atom"] for p in bridge.calls[0]["proofs"]) == [
        "Square_nonneg",
        "square_nonneg",
    ]
    paths = {
        a["lean_metadata"]["ai_proof_evidence"]["tactic_path"]
        for a in result["lean_cert"]["atoms"]
        if "lean_metadata" in a
    }
    assert len(paths) == 2
    assert all(Path(p).is_file() for p in paths)


def test_ai_proof_noop_without_unknowns(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path)
    gen = ScriptedGenerator([])
    result = run_ai_proof_repair(
        cert={"atoms": [{"name": "ok", "z3_check_result": "unsat"}]},
        mumei_lean_repo=repo,
        generator=gen,
    )
    assert result is None
    assert gen.requests == []


def test_ai_proof_uses_escalation_bundle_hints(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path)
    gen = ScriptedGenerator([_good_module()])
    bundle = {
        "source_file": "x.mm",
        "loop_line": 3,
        "loop_context": {},
        "reason": "cegis_max_iterations_reached",
        "atom": {"name": "square_nonneg", "requires": "true"},
        "counterexamples": [{"x": -1}],
        "tried_invariants": [{"expression": "x >= 0", "iteration": 1}],
    }
    with _patch_bridge(FakeBridge(["ok"])):
        run_ai_proof_repair(
            cert=_cert(),
            mumei_lean_repo=repo,
            generator=gen,
            escalation_bundle=bundle,
            evidence_dir=tmp_path / "e",
        )
    hints = gen.requests[0]["escalation_bundle"]
    assert hints["counterexamples"] == [{"x": -1}]
    assert hints["tried_invariants"][0]["expression"] == "x >= 0"
    assert hints["atom"]["name"] == "square_nonneg"
    prompt = lean_ai_proof.render_ai_proof_prompt(gen.requests[0])
    assert "square_nonneg_correct" in prompt
    assert "x >= 0" in prompt


def test_ai_proof_refuses_duplicate_atom_names(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path)
    cert = _cert()
    cert["atoms"].append(
        {"name": "square_nonneg", "z3_check_result": "unknown", "ensures": "result > 0"}
    )
    gen = ScriptedGenerator([_good_module(), _good_module()])
    with _patch_bridge() as bridge:
        result = run_ai_proof_repair(cert=cert, mumei_lean_repo=repo, generator=gen)
    assert result is not None
    bridge.assert_not_called()
    assert gen.requests == []
    assert result["success"] is False
    assert result["error_code"] == "ambiguous_atom_name"
    assert all(
        a["z3_check_result"] == "unknown"
        for a in result["lean_cert"]["atoms"]
        if a["name"] == "square_nonneg"
    )


# ---------------------------------------------------------------------------
# run_lean_bridge integration (Task 2-C stages first, then AI)
# ---------------------------------------------------------------------------


def test_run_lean_bridge_runs_ai_when_bridge_exits_zero_with_residual_unknown(
    tmp_path: Path,
) -> None:
    """`bridge.py` exits 0 for partial translations; residual unknowns still reach AI."""
    repo = _fake_repo(tmp_path)
    cert_path = tmp_path / "in.json"
    cert_path.write_text(json.dumps(_cert()), encoding="utf-8")
    lean_cert_out = tmp_path / "out.json"
    gen = ScriptedGenerator([_good_module()])

    def fake_bridge(*args, **kwargs):
        lean_cert_out.write_text(json.dumps(_cert()), encoding="utf-8")
        return MagicMock(returncode=0, stdout="partial translation", stderr="")

    with patch("agent.lean_bridge.subprocess.run", side_effect=fake_bridge), patch(
        "agent.lean_bridge.shutil.which", return_value="/usr/bin/lake"
    ), _patch_bridge(FakeBridge(["ok"])):
        result = lean_bridge.run_lean_bridge(
            cert_path=cert_path,
            lean_cert_out=lean_cert_out,
            mumei_lean_repo=repo,
            ai_proof_generator=gen,
            ai_proof_evidence_dir=tmp_path / "evidence",
        )

    assert len(gen.requests) == 1
    assert result["ai_proof_used"] is True
    atom = next(a for a in result["lean_cert"]["atoms"] if a["name"] == "square_nonneg")
    assert atom["z3_check_result"] == "lean_verified"
    on_disk = json.loads(lean_cert_out.read_text(encoding="utf-8"))
    disk_atom = next(a for a in on_disk["atoms"] if a["name"] == "square_nonneg")
    assert disk_atom["lean_metadata"]["ai_proof_used"] is True


def test_run_lean_bridge_ai_stage_after_known_witness(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path)
    (repo / "MumeiLean").mkdir()
    (repo / "MumeiLean" / "StdMathAbs.lean").write_text(
        "theorem abs_saturating_correct : True := by trivial\n", encoding="utf-8"
    )
    cert = _cert()
    cert["atoms"].append(
        {"name": "abs_saturating", "z3_check_result": "unknown"}
    )
    cert_path = tmp_path / "in.json"
    cert_path.write_text(json.dumps(cert), encoding="utf-8")
    gen = ScriptedGenerator([_good_module()])

    with patch("agent.lean_bridge.subprocess.run") as bridge_run, patch(
        "agent.lean_bridge.shutil.which", return_value="/usr/bin/lake"
    ), _patch_bridge(FakeBridge(["ok"])):
        bridge_run.side_effect = [
            MagicMock(returncode=1, stdout="", stderr="error: unsolved goals"),
            MagicMock(returncode=0, stdout="built", stderr=""),
        ]
        result = lean_bridge.run_lean_bridge(
            cert_path=cert_path,
            lean_cert_out=tmp_path / "out.json",
            mumei_lean_repo=repo,
            ai_proof_generator=gen,
            ai_proof_evidence_dir=tmp_path / "evidence",
        )

    assert result["success"] is True
    assert result["primary_error_code"] == "tactic_failed"
    assert result["fallback_strategy"] == AI_PROOF_STRATEGY
    assert result["ai_proof_used"] is True
    assert [s["name"] for s in result["strategy_attempts"]] == [
        "generated_bridge",
        "known_witness_module",
        AI_PROOF_STRATEGY,
    ]
    # AI stage only saw the residual atom, not the known witness one
    assert gen.requests[0]["atom"]["name"] == "square_nonneg"
    assert len(gen.requests) == 1
    atoms = {a["name"]: a for a in result["lean_cert"]["atoms"]}
    assert atoms["abs_saturating"]["lean_metadata"]["known_witness_used"] is True
    assert atoms["abs_saturating"]["lean_metadata"].get("ai_proof_used") is None
    assert atoms["square_nonneg"]["lean_metadata"]["ai_proof_used"] is True
    assert atoms["square_nonneg"]["lean_metadata"]["known_witness_used"] is False

    merged = lean_bridge.merge_lean_cert_into_proof_cert(cert, result["lean_cert"])
    assert lean_bridge.count_lean_verified_unknowns(cert, merged) == 2
    assert cert["atoms"][1]["z3_check_result"] == "unknown"  # non-mutating


def test_run_lean_bridge_ai_partial_success_reported(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path)
    cert = _cert()
    cert["atoms"].append(
        {"name": "hard_one", "z3_check_result": "unknown", "ensures": "false"}
    )
    cert_path = tmp_path / "in.json"
    cert_path.write_text(json.dumps(cert), encoding="utf-8")
    gen = ScriptedGenerator(
        [_good_module(), "theorem hard_one_correct : False := by sorry"]
    )

    with patch("agent.lean_bridge.subprocess.run") as bridge_run, patch(
        "agent.lean_bridge.shutil.which", return_value="/usr/bin/lake"
    ), _patch_bridge(FakeBridge(["ok"])):
        bridge_run.return_value = MagicMock(
            returncode=1, stdout="", stderr="error: unsolved goals"
        )
        result = lean_bridge.run_lean_bridge(
            cert_path=cert_path,
            lean_cert_out=tmp_path / "out.json",
            mumei_lean_repo=repo,
            ai_proof_generator=gen,
            ai_proof_max_attempts=1,
            ai_proof_evidence_dir=tmp_path / "evidence",
        )

    assert result["success"] is False
    assert result["returncode"] != 0
    assert result["partial_success"] is True
    assert result["ai_proof_used"] is True
    assert result["ai_proof_residual"] == ["hard_one"]
    atoms = {a["name"]: a for a in result["lean_cert"]["atoms"]}
    assert atoms["square_nonneg"]["z3_check_result"] == "lean_verified"
    assert atoms["hard_one"]["z3_check_result"] == "unknown"
    # failed AI attempt is recorded on the residual atom for the human fallback
    outcome = atoms["hard_one"]["ai_proof_outcome"]
    assert outcome["proved"] is False
    assert outcome["error_code"] == "no_trusted_statement"
    from agent import human_review as hr

    stages = hr.HumanReviewTracker._prior_lean_stages(atoms["hard_one"])
    assert stages["ai_generated_proof"] is True
    assert stages["ai_proof_error_code"] == "no_trusted_statement"
    on_disk = json.loads((tmp_path / "out.json").read_text(encoding="utf-8"))
    disk_hard = next(a for a in on_disk["atoms"] if a["name"] == "hard_one")
    assert disk_hard["ai_proof_outcome"]["error_code"] == "no_trusted_statement"


def test_run_lean_bridge_ai_failure_after_bridge_exit_zero_is_nonzero(
    tmp_path: Path,
) -> None:
    repo = _fake_repo(tmp_path)
    cert_path = tmp_path / "in.json"
    cert_path.write_text(json.dumps(_cert()), encoding="utf-8")
    lean_cert_out = tmp_path / "out.json"
    gen = ScriptedGenerator(["```lean\n  sorry\n```"])

    def fake_bridge(*args, **kwargs):
        lean_cert_out.write_text(json.dumps(_cert()), encoding="utf-8")
        return MagicMock(returncode=0, stdout="partial translation", stderr="")

    with patch("agent.lean_bridge.subprocess.run", side_effect=fake_bridge), patch(
        "agent.lean_bridge.shutil.which", return_value="/usr/bin/lake"
    ), _patch_bridge(FakeBridge(["unsolved"])):
        result = lean_bridge.run_lean_bridge(
            cert_path=cert_path,
            lean_cert_out=lean_cert_out,
            mumei_lean_repo=repo,
            ai_proof_generator=gen,
            ai_proof_max_attempts=1,
        )
    assert result["success"] is False
    assert result["returncode"] != 0


def test_run_lean_bridge_writes_requested_cert_when_only_ai_succeeds(
    tmp_path: Path,
) -> None:
    """bridge.py failing before writing its cert must not lose the AI upgrade."""
    repo = _fake_repo(tmp_path)
    cert_path = tmp_path / "in.json"
    cert_path.write_text(json.dumps(_cert()), encoding="utf-8")
    lean_cert_out = tmp_path / "out.json"
    gen = ScriptedGenerator([_good_module()])

    with patch("agent.lean_bridge.subprocess.run") as bridge_run, patch(
        "agent.lean_bridge.shutil.which", return_value="/usr/bin/lake"
    ), _patch_bridge(FakeBridge(["ok"])):
        bridge_run.return_value = MagicMock(
            returncode=1, stdout="", stderr="error: unsolved goals"
        )
        result = lean_bridge.run_lean_bridge(
            cert_path=cert_path,
            lean_cert_out=lean_cert_out,
            mumei_lean_repo=repo,
            ai_proof_generator=gen,
            ai_proof_evidence_dir=tmp_path / "evidence",
        )
    assert result["success"] is True
    assert result["lean_cert_path"] == str(lean_cert_out)
    on_disk = json.loads(lean_cert_out.read_text(encoding="utf-8"))
    atom = next(a for a in on_disk["atoms"] if a["name"] == "square_nonneg")
    assert atom["z3_check_result"] == "lean_verified"


def test_run_lean_bridge_without_generator_is_unchanged(tmp_path: Path) -> None:
    repo = _fake_repo(tmp_path)
    cert_path = tmp_path / "in.json"
    cert_path.write_text(json.dumps(_cert()), encoding="utf-8")

    with patch("agent.lean_bridge.subprocess.run") as bridge_run, patch(
        "agent.lean_bridge.shutil.which", return_value="/usr/bin/lake"
    ), patch("agent.lean_ai_proof.run_ai_proof_repair") as ai:
        bridge_run.return_value = MagicMock(
            returncode=1, stdout="", stderr="error: unsolved goals"
        )
        result = lean_bridge.run_lean_bridge(
            cert_path=cert_path,
            lean_cert_out=tmp_path / "out.json",
            mumei_lean_repo=repo,
        )

    ai.assert_not_called()
    assert result["success"] is False
    assert result["error_code"] == "tactic_failed"
    assert "ai_proof_used" not in result


# ---------------------------------------------------------------------------
# config gating: no-LLM / CI_FIXTURE_MODE skip
# ---------------------------------------------------------------------------


def test_lean_ai_proof_active_requires_flag_key_and_no_fixture_mode(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.delenv("CI_FIXTURE_MODE", raising=False)
    cfg = AgentConfig(api_key="k", enable_lean_ai_proof=True, ci_fixture_mode=False)
    assert cfg.lean_ai_proof_active() is True
    assert AgentConfig(api_key="", enable_lean_ai_proof=True).lean_ai_proof_active() is False
    assert AgentConfig(api_key="k", enable_lean_ai_proof=False).lean_ai_proof_active() is False
    assert (
        AgentConfig(api_key="k", enable_lean_ai_proof=True, ci_fixture_mode=True)
        .lean_ai_proof_active()
        is False
    )


def test_proliferate_generator_factory_respects_gating() -> None:
    from agent.proliferate import _lean_ai_proof_generator

    assert _lean_ai_proof_generator(AgentConfig(api_key="", enable_lean_ai_proof=True)) is None
    assert (
        _lean_ai_proof_generator(
            AgentConfig(api_key="k", enable_lean_ai_proof=True, ci_fixture_mode=True)
        )
        is None
    )
    gen = _lean_ai_proof_generator(
        AgentConfig(api_key="k", enable_lean_ai_proof=True, ci_fixture_mode=False)
    )
    assert isinstance(gen, lean_ai_proof.LLMAiProofGenerator)


def test_run_lean_fallback_inner_records_ai_provenance(tmp_path: Path) -> None:
    from agent.proliferate import _run_lean_fallback_inner

    repo = _fake_repo(tmp_path)
    results = [{"publish_result": {"proof_certificate": _cert()}}]
    gen = ScriptedGenerator([_good_module()])

    with patch("agent.lean_bridge.subprocess.run") as bridge_run, patch(
        "agent.lean_bridge.shutil.which", return_value="/usr/bin/lake"
    ), _patch_bridge(FakeBridge(["ok"])):
        bridge_run.return_value = MagicMock(
            returncode=1, stdout="", stderr="error: unsolved goals"
        )
        _run_lean_fallback_inner(
            results,
            mumei_lean_repo=str(repo),
            ai_proof_generator=gen,
            ai_proof_evidence_dir=str(tmp_path / "evidence"),
        )

    fallback = results[0]["lean_fallback"]
    assert fallback["proved"] == 1
    assert fallback["failed"] == 0
    assert fallback["success"] is True
    assert fallback["ai_proof_used"] is True
    assert fallback["ai_proof_residual"] == []
    assert fallback["fallback_strategy"] == AI_PROOF_STRATEGY
    upgraded = results[0]["publish_result"]["proof_certificate"]
    assert upgraded["atoms"][1]["z3_check_result"] == "lean_verified"
    assert upgraded["all_verified"] is True


def test_run_lean_fallback_inner_without_generator_has_no_ai_keys(tmp_path: Path) -> None:
    from agent.proliferate import _run_lean_fallback_inner

    repo = _fake_repo(tmp_path)
    results = [{"publish_result": {"proof_certificate": _cert()}}]

    with patch("agent.lean_bridge.subprocess.run") as bridge_run, patch(
        "agent.lean_bridge.shutil.which", return_value="/usr/bin/lake"
    ):
        bridge_run.return_value = MagicMock(
            returncode=1, stdout="", stderr="error: unsolved goals"
        )
        _run_lean_fallback_inner(results, mumei_lean_repo=str(repo))

    fallback = results[0]["lean_fallback"]
    assert fallback["proved"] == 0
    assert "ai_proof_used" not in fallback
    assert results[0]["publish_result"]["proof_certificate"]["atoms"][1][
        "z3_check_result"
    ] == "unknown"
