"""End-to-end smoke tests for the forge mode.

Requires a real mumei binary; marked as ``integration`` so it's
excluded from the default pytest run (same pattern as the existing
``test_publish_e2e`` / ``test_integration_e2e`` suites).
"""
from __future__ import annotations

import json
from pathlib import Path
from unittest.mock import MagicMock

import pytest

from agent.forge import MumeiForge


pytestmark = pytest.mark.integration


_TARGET_BEFORE = (
    "// generated by test_forge_e2e\n\n"
    "atom safe_subtract(a: i64, b: i64)\n"
    "    requires: a >= b;\n"
    "    ensures: result >= 0 && result == a - b;\n"
    "    body: a - b;\n"
)


def _make_client(response_text: str) -> MagicMock:
    client = MagicMock()
    message = MagicMock()
    message.content = response_text
    choice = MagicMock()
    choice.message = message
    resp = MagicMock()
    resp.choices = [choice]
    client.chat.completions.create.return_value = resp
    return client


def _make_config():
    cfg = MagicMock()
    cfg.mumei_bin = "mumei"
    cfg.model = "test-model"
    cfg.max_retries = 2
    cfg.create_client.return_value = MagicMock()
    return cfg


def test_forge_append_end_to_end(
    tmp_path: Path,
    real_mumei_client,
):
    """Append a real atom to a real .mm file and verify with mumei."""
    repo = tmp_path / "repo"
    std = repo / "std"
    std.mkdir(parents=True)
    target = std / "test_mod.mm"
    target.write_text(_TARGET_BEFORE, encoding="utf-8")

    tasks_dir = tmp_path / "forge_tasks"
    tasks_dir.mkdir()
    spec_path = tasks_dir / "add.json"
    spec_path.write_text(
        json.dumps({
            "task_id": "e2e-safe-add",
            "target_file": "std/test_mod.mm",
            "mode": "append",
            "atoms": [{
                "name": "safe_add_e2e",
                "inputs": [{"name": "a", "type": "i64"}, {"name": "b", "type": "i64"}],
                "requires": "a >= 0 && b >= 0",
                "ensures": "result == a + b && result >= 0",
                "reference_patterns": ["safe_subtract"],
            }],
            "max_retries": 1,
            "auto_commit": False,
        }),
        encoding="utf-8",
    )

    snippet = (
        "atom safe_add_e2e(a: i64, b: i64)\n"
        "    requires: a >= 0 && b >= 0;\n"
        "    ensures: result >= 0 && result == a + b;\n"
        "    body: a + b;\n"
    )

    forge = MumeiForge(
        config=_make_config(),
        mumei_client=real_mumei_client,
        mumei_repo_dir=repo,
        forge_tasks_dir=tasks_dir,
        log_path=tmp_path / "forge_log.json",
        openai_client=_make_client(f"```mumei\n{snippet}```"),
    )

    results = forge.run(max_tasks=1, auto_commit_override=False)
    assert len(results) == 1
    assert results[0].status == "success", results[0].error
    assert "safe_add_e2e" in target.read_text(encoding="utf-8")

    # Log was written.
    log = json.loads((tmp_path / "forge_log.json").read_text(encoding="utf-8"))
    assert log["runs"][0]["task_id"] == "e2e-safe-add"
    assert log["runs"][0]["status"] == "success"
