"""Static validation tests for generated FFI wrappers (SI-3 verification).

These tests validate the *content* of generated C headers, Rust wrappers,
and Python wrappers without requiring the mumei binary.  They check
structural properties that any correct emit output must satisfy.

Run with: pytest tests/test_wrapper_validation.py
"""
from __future__ import annotations

import re
import textwrap



# ---------------------------------------------------------------------------
# Sample generated wrapper content (representative of mumei emit output)
# ---------------------------------------------------------------------------

SAMPLE_C_HEADER = textwrap.dedent("""\
    #ifndef SAFE_ADD_H
    #define SAFE_ADD_H

    #include <stdint.h>

    #ifdef __cplusplus
    extern "C" {
    #endif

    /** @brief Add two non-negative numbers.
     *  @pre a >= 0 && b >= 0
     *  @post result == a + b
     */
    int64_t safe_add(int64_t a, int64_t b);

    #ifdef __cplusplus
    }
    #endif

    #endif /* SAFE_ADD_H */
""")

SAMPLE_C_HEADER_MULTI = textwrap.dedent("""\
    #ifndef PAYMENT_H
    #define PAYMENT_H

    #include <stdint.h>

    #ifdef __cplusplus
    extern "C" {
    #endif

    /** @brief Calculate subtotal from quantity and unit price.
     *  @pre quantity > 0 && price > 0
     *  @post result > 0
     */
    int64_t calc_subtotal(int64_t quantity, int64_t price);

    /** @brief Calculate tax amount.
     *  @pre amount > 0 && rate >= 0 && rate <= 100
     *  @post result >= 0
     */
    int64_t calc_tax(int64_t amount, int64_t rate);

    /** @brief Calculate total by adding subtotal and tax.
     *  @pre subtotal > 0 && tax >= 0
     *  @post result >= subtotal
     */
    int64_t calc_total(int64_t subtotal, int64_t tax);

    #ifdef __cplusplus
    }
    #endif

    #endif /* PAYMENT_H */
""")

SAMPLE_RUST_WRAPPER = textwrap.dedent("""\
    //! FFI bindings for safe_add (auto-generated by mumei)

    extern "C" {
        /// Add two non-negative numbers.
        /// requires: a >= 0 && b >= 0
        /// ensures: result == a + b
        fn safe_add(a: i64, b: i64) -> i64;
    }

    /// Safe wrapper for `safe_add`.
    pub fn safe_add_checked(a: i64, b: i64) -> Option<i64> {
        if a >= 0 && b >= 0 {
            Some(unsafe { safe_add(a, b) })
        } else {
            None
        }
    }
""")

SAMPLE_RUST_WRAPPER_MULTI = textwrap.dedent("""\
    //! FFI bindings for payment module (auto-generated by mumei)

    extern "C" {
        fn calc_subtotal(quantity: i64, price: i64) -> i64;
        fn calc_tax(amount: i64, rate: i64) -> i64;
        fn calc_total(subtotal: i64, tax: i64) -> i64;
    }

    pub fn calc_subtotal_checked(quantity: i64, price: i64) -> Option<i64> {
        if quantity > 0 && price > 0 {
            Some(unsafe { calc_subtotal(quantity, price) })
        } else {
            None
        }
    }

    pub fn calc_tax_checked(amount: i64, rate: i64) -> Option<i64> {
        if amount > 0 && rate >= 0 && rate <= 100 {
            Some(unsafe { calc_tax(amount, rate) })
        } else {
            None
        }
    }

    pub fn calc_total_checked(subtotal: i64, tax: i64) -> Option<i64> {
        if subtotal > 0 && tax >= 0 {
            Some(unsafe { calc_total(subtotal, tax) })
        } else {
            None
        }
    }
""")

SAMPLE_PYTHON_WRAPPER = textwrap.dedent("""\
    \"\"\"FFI wrapper for safe_add (auto-generated by mumei).\"\"\"
    import ctypes
    from pathlib import Path

    _LIB_PATH = Path(__file__).parent / "libsafe_add.so"
    _lib = ctypes.CDLL(str(_LIB_PATH))

    _lib.safe_add.argtypes = [ctypes.c_int64, ctypes.c_int64]
    _lib.safe_add.restype = ctypes.c_int64


    def safe_add(a: int, b: int) -> int:
        \"\"\"Add two non-negative numbers.

        Requires: a >= 0 && b >= 0
        Ensures: result == a + b
        \"\"\"
        return _lib.safe_add(a, b)
""")

SAMPLE_PYTHON_WRAPPER_MULTI = textwrap.dedent("""\
    \"\"\"FFI wrapper for payment module (auto-generated by mumei).\"\"\"
    import ctypes
    from pathlib import Path

    _LIB_PATH = Path(__file__).parent / "libpayment.so"
    _lib = ctypes.CDLL(str(_LIB_PATH))

    _lib.calc_subtotal.argtypes = [ctypes.c_int64, ctypes.c_int64]
    _lib.calc_subtotal.restype = ctypes.c_int64

    _lib.calc_tax.argtypes = [ctypes.c_int64, ctypes.c_int64]
    _lib.calc_tax.restype = ctypes.c_int64

    _lib.calc_total.argtypes = [ctypes.c_int64, ctypes.c_int64]
    _lib.calc_total.restype = ctypes.c_int64


    def calc_subtotal(quantity: int, price: int) -> int:
        return _lib.calc_subtotal(quantity, price)

    def calc_tax(amount: int, rate: int) -> int:
        return _lib.calc_tax(amount, rate)

    def calc_total(subtotal: int, tax: int) -> int:
        return _lib.calc_total(subtotal, tax)
""")


# ---------------------------------------------------------------------------
# C Header validation
# ---------------------------------------------------------------------------


class TestCHeaderValidation:
    """Validate structural properties of generated C headers."""

    def test_include_guard_present(self):
        assert "#ifndef SAFE_ADD_H" in SAMPLE_C_HEADER
        assert "#define SAFE_ADD_H" in SAMPLE_C_HEADER
        assert "#endif" in SAMPLE_C_HEADER

    def test_include_guard_pattern(self):
        """Include guard follows #ifndef NAME_H / #define NAME_H pattern."""
        match = re.search(r"#ifndef\s+(\w+_H)\s*\n#define\s+(\w+_H)", SAMPLE_C_HEADER)
        assert match is not None
        assert match.group(1) == match.group(2)

    def test_stdint_included(self):
        assert "#include <stdint.h>" in SAMPLE_C_HEADER

    def test_function_declaration_present(self):
        assert re.search(r"int64_t\s+safe_add\s*\(", SAMPLE_C_HEADER) is not None

    def test_extern_c_block(self):
        assert 'extern "C"' in SAMPLE_C_HEADER

    def test_doxygen_pre_post(self):
        """Doxygen @pre and @post annotations are present."""
        assert "@pre" in SAMPLE_C_HEADER
        assert "@post" in SAMPLE_C_HEADER

    def test_multi_atom_header_has_all_functions(self):
        """Multi-atom header declares all functions."""
        assert re.search(r"int64_t\s+calc_subtotal\s*\(", SAMPLE_C_HEADER_MULTI)
        assert re.search(r"int64_t\s+calc_tax\s*\(", SAMPLE_C_HEADER_MULTI)
        assert re.search(r"int64_t\s+calc_total\s*\(", SAMPLE_C_HEADER_MULTI)

    def test_multi_atom_header_single_guard(self):
        """Multi-atom header has exactly one include guard pair."""
        ifndef_count = SAMPLE_C_HEADER_MULTI.count("#ifndef")
        define_count = SAMPLE_C_HEADER_MULTI.count("#define PAYMENT_H")
        assert ifndef_count == 1
        assert define_count == 1


# ---------------------------------------------------------------------------
# Rust Wrapper validation
# ---------------------------------------------------------------------------


class TestRustWrapperValidation:
    """Validate structural properties of generated Rust wrappers."""

    def test_extern_c_block_present(self):
        assert 'extern "C"' in SAMPLE_RUST_WRAPPER

    def test_function_in_extern_block(self):
        """FFI function declared inside extern "C" block."""
        # Match: fn <name>(...) -> <type>;  inside extern "C" { ... }
        extern_block = re.search(
            r'extern\s+"C"\s*\{(.*?)\}',
            SAMPLE_RUST_WRAPPER,
            re.DOTALL,
        )
        assert extern_block is not None
        assert "fn safe_add" in extern_block.group(1)

    def test_safe_wrapper_present(self):
        """Safe (checked) wrapper function exists."""
        assert "pub fn safe_add_checked" in SAMPLE_RUST_WRAPPER

    def test_unsafe_call_in_wrapper(self):
        """Safe wrapper uses unsafe block to call FFI function."""
        assert "unsafe { safe_add(" in SAMPLE_RUST_WRAPPER

    def test_option_return_type(self):
        """Safe wrapper returns Option<i64>."""
        assert "-> Option<i64>" in SAMPLE_RUST_WRAPPER

    def test_multi_atom_extern_block(self):
        """Multi-atom wrapper has all functions in extern block."""
        extern_block = re.search(
            r'extern\s+"C"\s*\{(.*?)\}',
            SAMPLE_RUST_WRAPPER_MULTI,
            re.DOTALL,
        )
        assert extern_block is not None
        block_content = extern_block.group(1)
        assert "fn calc_subtotal" in block_content
        assert "fn calc_tax" in block_content
        assert "fn calc_total" in block_content

    def test_multi_atom_safe_wrappers(self):
        """Each atom has a safe wrapper function."""
        assert "pub fn calc_subtotal_checked" in SAMPLE_RUST_WRAPPER_MULTI
        assert "pub fn calc_tax_checked" in SAMPLE_RUST_WRAPPER_MULTI
        assert "pub fn calc_total_checked" in SAMPLE_RUST_WRAPPER_MULTI


# ---------------------------------------------------------------------------
# Python Wrapper validation
# ---------------------------------------------------------------------------


class TestPythonWrapperValidation:
    """Validate structural properties of generated Python wrappers."""

    def test_ctypes_import(self):
        assert "import ctypes" in SAMPLE_PYTHON_WRAPPER

    def test_cdll_loading(self):
        """Shared library is loaded via ctypes.CDLL."""
        assert "ctypes.CDLL" in SAMPLE_PYTHON_WRAPPER

    def test_argtypes_defined(self):
        """Function argument types are defined."""
        assert ".argtypes" in SAMPLE_PYTHON_WRAPPER
        assert "ctypes.c_int64" in SAMPLE_PYTHON_WRAPPER

    def test_restype_defined(self):
        """Function return type is defined."""
        assert ".restype" in SAMPLE_PYTHON_WRAPPER

    def test_python_function_defined(self):
        """Pythonic wrapper function is defined."""
        assert "def safe_add(" in SAMPLE_PYTHON_WRAPPER

    def test_type_hints_present(self):
        """Python function has type hints."""
        assert "a: int" in SAMPLE_PYTHON_WRAPPER
        assert "-> int" in SAMPLE_PYTHON_WRAPPER

    def test_docstring_with_contracts(self):
        """Python function has docstring with contract information."""
        assert "Requires:" in SAMPLE_PYTHON_WRAPPER
        assert "Ensures:" in SAMPLE_PYTHON_WRAPPER

    def test_valid_python_syntax(self):
        """Generated Python wrapper is valid Python syntax."""
        import ast
        ast.parse(SAMPLE_PYTHON_WRAPPER)

    def test_multi_atom_wrapper_functions(self):
        """Multi-atom wrapper defines all functions."""
        assert "def calc_subtotal(" in SAMPLE_PYTHON_WRAPPER_MULTI
        assert "def calc_tax(" in SAMPLE_PYTHON_WRAPPER_MULTI
        assert "def calc_total(" in SAMPLE_PYTHON_WRAPPER_MULTI

    def test_multi_atom_argtypes(self):
        """Each function has argtypes defined."""
        assert SAMPLE_PYTHON_WRAPPER_MULTI.count(".argtypes") == 3
        assert SAMPLE_PYTHON_WRAPPER_MULTI.count(".restype") == 3

    def test_multi_atom_valid_python_syntax(self):
        """Multi-atom wrapper is valid Python syntax."""
        import ast
        ast.parse(SAMPLE_PYTHON_WRAPPER_MULTI)


# ---------------------------------------------------------------------------
# Cross-wrapper consistency checks
# ---------------------------------------------------------------------------


class TestCrossWrapperConsistency:
    """Verify consistency across C, Rust, and Python wrappers."""

    def test_function_name_consistency(self):
        """Same function name appears in all three wrappers."""
        assert "safe_add" in SAMPLE_C_HEADER
        assert "safe_add" in SAMPLE_RUST_WRAPPER
        assert "safe_add" in SAMPLE_PYTHON_WRAPPER

    def test_parameter_count_consistency(self):
        """All wrappers declare the same number of parameters."""
        # C: int64_t safe_add(int64_t a, int64_t b)
        c_params = re.search(r"safe_add\((.*?)\)", SAMPLE_C_HEADER)
        assert c_params is not None
        c_count = c_params.group(1).count(",") + 1

        # Rust: fn safe_add(a: i64, b: i64)
        rust_params = re.search(r"fn safe_add\((.*?)\)", SAMPLE_RUST_WRAPPER)
        assert rust_params is not None
        rust_count = rust_params.group(1).count(",") + 1

        # Python: def safe_add(a: int, b: int)
        py_params = re.search(r"def safe_add\((.*?)\)", SAMPLE_PYTHON_WRAPPER)
        assert py_params is not None
        # Exclude self parameter if present
        py_count = py_params.group(1).count(",") + 1

        assert c_count == rust_count == py_count == 2

    def test_multi_atom_function_count_consistency(self):
        """All multi-atom wrappers declare the same number of functions."""
        c_fns = len(re.findall(r"int64_t\s+\w+\s*\(", SAMPLE_C_HEADER_MULTI))
        rust_fns = len(re.findall(r"fn\s+calc_\w+\s*\(", SAMPLE_RUST_WRAPPER_MULTI))
        py_fns = len(re.findall(r"def\s+calc_\w+\s*\(", SAMPLE_PYTHON_WRAPPER_MULTI))

        assert c_fns == 3
        assert rust_fns >= 3  # Rust has both extern and safe wrappers
        assert py_fns == 3
